@startuml notification-system-with-email

package "Notification Module" {
    [NotificationModule] --> [EmailModule]
}

package "Email Module" {
    [email-service]
    [send-email-service]
    [email-template-repository]
    [email-notification-repository]

    [EmailModule] -down-> [email-service]
    [EmailModule] -down-> [send-email-service]
    [email-service] --> [email-template-repository]
    [email-service] --> [email-notification-repository]
    [send-email-service] --> [email-notification-repository]
    [send-email-service] --> [email-template-repository]
}

@enduml