@startuml notification-system-with-email

package "Notification Module" {
  [NotificationService]
}

package "Email Module" {
  [EmailService]
  note right of [EmailService]
    + createNotification()
  end note

  [SendEmailService]
  note right of [SendEmailService]
    + sendEmail()
  end note

  [EmailTemplatesRepository]
  [EmailNotificationsRepository]

  [EmailService] --> [EmailTemplatesRepository]
  [EmailService] --> [EmailNotificationsRepository]
  [SendEmailService] --> [EmailTemplatesRepository]
  [SendEmailService] --> [EmailNotificationsRepository]
}

[NotificationService] --> [EmailService]
[NotificationService] --> [SendEmailService]
@enduml